--- #YAML:1.0
name:               Catalyst-View-PNGTTGraph
version:            0.021
abstract:           PNG Graph View Component for Catalyst
author:
    - Terence Monteiro <terencemo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::View::SVGTTGraph:  0.011
    Image::LibRSVG:       0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
